### ISSUE TITLE
Diet Tracker for Assets

### ISSUE THREAD

**Issue by jackdixonryan** [Front-Range-Foundry/asset-tracking#9]
The Assets must eat. 

The park offers some main meals for the animals to consume. We will need to register them as: 
- [x] Beef (processed) 
- [x] Whole Entire Goat 
- [x] Big ol' cycad leaves
- [x] Berries for the wee ones
- [x] Tubers for the rootie tooters
- [x] Fish for the kind of animal that likes that I guess
- [x] Big fruits
- [x] Nuts, some animals like nuts
- [x] Grain, grass, hay

For each feeding, the keeper will need to log: 
- [x] What feed they used
- [x] How much they offered
- [x] When they fed the asset

Additionally, the animal's species should dictate what kind of food they get. The keeper should experience an error if they attempt to log a feeding session that does not have the appropriate food type.
